version: '3.4'
services:
  finderbe-docker:
    image: finderbe
    container_name: finderbe-docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - PASSWORD_ENV_SEEDED=jadlljames
    ports:
      - 8080:80
      - 8081:443
    environment:
      - PASSWORD_ENV_SEEDED=jadlljames
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=jadlljames
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - my-network
    depends_on:
      - database
  
  database:
    image: mysql
    container_name: mysql
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jadlljames
      MYSQL_USER: root
      MYSQL_DATABASE: users
    networks:
      - my-network

networks:
  my-network:  # Define the custom network here
    driver: bridge
volumes:
  db-volume: